version: '2'
services:
    beingsre-app:
        image: beingsre
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://beingsre-mysql:3306/beingsre?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://beingsre-elasticsearch:9200
        ports:
            - 8080:8080
    beingsre-mysql:
        extends:
            file: mysql.yml
            service: beingsre-mysql
    beingsre-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: beingsre-elasticsearch
